const express=require('express');const path=require('path');const Database=require('better-sqlite3');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');
const app=express();app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
const DATA_DIR=path.join(__dirname,'data'); require('fs').mkdirSync(DATA_DIR,{recursive:true}); const db=new Database(path.join(DATA_DIR,'data.db'));db.pragma('journal_mode=WAL');
const SECRET=process.env.JWT_SECRET||'dev-only-change-this-secret';
const OWNER_EMAIL=process.env.OWNER_EMAIL||'amankeshri7585@gmail.com';const OWNER_PASSWORD=process.env.OWNER_PASSWORD||'Aman2004@#';
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS subjects(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL);CREATE TABLE IF NOT EXISTS tests(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,subject_id INTEGER,time_minutes INTEGER NOT NULL DEFAULT 10,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS questions(id INTEGER PRIMARY KEY AUTOINCREMENT,test_id INTEGER,subject_id INTEGER,topic TEXT,question TEXT NOT NULL,a TEXT NOT NULL,b TEXT NOT NULL,c TEXT NOT NULL,d TEXT NOT NULL,correct INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS results(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,test_id INTEGER,score INTEGER,total INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
if(!db.prepare('SELECT id FROM users WHERE email=?').get(OWNER_EMAIL)){db.prepare('INSERT INTO users(name,email,password,role) VALUES(?,?,?,?)').run('Owner',OWNER_EMAIL,bcrypt.hashSync(OWNER_PASSWORD,10),'owner')}
for (const name of ['General Knowledge','History','Geography','Polity','Science','Computer']) { db.prepare('INSERT OR IGNORE INTO subjects(name) VALUES(?)').run(name); }
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Login required'});req.user=jwt.verify(h.slice(7),SECRET);next()}catch(e){res.status(401).json({error:'Invalid or expired session'})}}
function owner(req,res,next){if(req.user.role!=='owner')return res.status(403).json({error:'Owner access required'});next()}
app.post('/api/auth/register',(req,res)=>{const {name,email,password}=req.body;if(!name||!email||!password||password.length<6)return res.status(400).json({error:'Name, email and password (6+ chars) required'});try{const info=db.prepare('INSERT INTO users(name,email,password) VALUES(?,?,?)').run(name,email.toLowerCase(),bcrypt.hashSync(password,10));const user={id:info.lastInsertRowid,name,email:email.toLowerCase(),role:'user'};res.json({user,token:jwt.sign(user,SECRET,{expiresIn:'7d'})})}catch(e){res.status(409).json({error:'Email already registered'})}});
app.post('/api/auth/login',(req,res)=>{const {email,password}=req.body;const u=db.prepare('SELECT * FROM users WHERE email=?').get((email||'').toLowerCase());if(!u||!bcrypt.compareSync(password||'',u.password))return res.status(401).json({error:'Invalid email or password'});const user={id:u.id,name:u.name,email:u.email,role:u.role};res.json({user,token:jwt.sign(user,SECRET,{expiresIn:'7d'})})});
app.get('/api/me',auth,(req,res)=>res.json(req.user));
app.get('/api/subjects',(req,res)=>res.json(db.prepare('SELECT * FROM subjects ORDER BY name').all()));
app.get('/api/tests',(req,res)=>res.json(db.prepare('SELECT t.id,t.name,t.time_minutes,s.name subject,(SELECT COUNT(*) FROM questions q WHERE q.test_id=t.id) questions FROM tests t LEFT JOIN subjects s ON s.id=t.subject_id ORDER BY t.id DESC').all()));
app.get('/api/admin/tests',auth,owner,(req,res)=>res.json(db.prepare('SELECT t.id,t.name,t.time_minutes,t.subject_id,s.name subject,(SELECT COUNT(*) FROM questions q WHERE q.test_id=t.id) questions FROM tests t LEFT JOIN subjects s ON s.id=t.subject_id ORDER BY t.id DESC').all()));
app.get('/api/health',(req,res)=>res.json({ok:true,service:'test-wala'}));
app.get('/api/tests/:id',auth,(req,res)=>{const t=db.prepare('SELECT t.id,t.name,t.time_minutes,s.name subject FROM tests t LEFT JOIN subjects s ON s.id=t.subject_id WHERE t.id=?').get(req.params.id);if(!t)return res.status(404).json({error:'Test not found'});const qs=db.prepare('SELECT id,question,a,b,c,d FROM questions WHERE test_id=? ORDER BY id').all(req.params.id);res.json({...t,questions:qs})});
app.post('/api/results',auth,(req,res)=>{const {testId,score,total}=req.body;const info=db.prepare('INSERT INTO results(user_id,test_id,score,total) VALUES(?,?,?,?)').run(req.user.id,testId,score,total);res.json({id:info.lastInsertRowid})});
app.get('/api/my-results',auth,(req,res)=>res.json(db.prepare('SELECT r.*,t.name test_name FROM results r JOIN tests t ON t.id=r.test_id WHERE r.user_id=? ORDER BY r.id DESC').all(req.user.id)));
app.post('/api/admin/subjects',auth,owner,(req,res)=>{try{const info=db.prepare('INSERT INTO subjects(name) VALUES(?)').run(req.body.name.trim());res.json({id:info.lastInsertRowid})}catch(e){res.status(409).json({error:'Subject exists'})}});
app.post('/api/admin/tests',auth,owner,(req,res)=>{const {name,subjectId,timeMinutes}=req.body;const info=db.prepare('INSERT INTO tests(name,subject_id,time_minutes) VALUES(?,?,?)').run(name,subjectId||null,timeMinutes||10);res.json({id:info.lastInsertRowid})});
app.post('/api/admin/questions',auth,owner,(req,res)=>{const {testId,subjectId,topic,question,a,b,c,d,correct}=req.body;if(!testId||!question||[a,b,c,d].some(x=>!x))return res.status(400).json({error:'Complete question required'});const info=db.prepare('INSERT INTO questions(test_id,subject_id,topic,question,a,b,c,d,correct) VALUES(?,?,?,?,?,?,?,?,?)').run(testId,subjectId||null,topic||'',question,a,b,c,d,correct);res.json({id:info.lastInsertRowid})});
app.get('/api/admin/stats',auth,owner,(req,res)=>res.json({users:db.prepare("SELECT COUNT(*) c FROM users WHERE role='user'").get().c,tests:db.prepare('SELECT COUNT(*) c FROM tests').get().c,questions:db.prepare('SELECT COUNT(*) c FROM questions').get().c,results:db.prepare('SELECT COUNT(*) c FROM results').get().c}));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(process.env.PORT||3000, '0.0.0.0', ()=>console.log('Test Wala running on port '+ (process.env.PORT||3000)));
